name: Updates Docs
on:
  push:
    branches:
      - master
jobs:
  update-docs:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'docs') || contains(github.event.head_commit.message, 'documentation')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
